"""
English language translation
"""
en = {
    "projectname": "Bosch",
    "wrong_username": "Wrong username or password.",
    "login_successful": "Login successful.",
    "blocked_account": "Sorry your account has been blocked. Kindly contact your administrator.",
    "data_retrived": "Data retrived successfully.",
    "menu_home": "HOME",
	"menu_customer_uploads": "AGENT BULK UPLOAD",
	"menu_dashboard": "DASHBOARD",
	"menu_transactions": "TRANSACTIONS",
	"menu_admins": "USERS",
	"menu_dist": "DISTRIBUTORS",
    "menu_dealer_activity": "DEALER ACTIVITY",
    "menu_tools": "TOOLS",
    "menu_customers": "ARTISANS",
    "menu_dealers": "DEALERS",
    "dealer": "DEALER",
    "menu_payment": "PAYMENTS",
    "menu_transactions": "TRANSACTIONS",
    "upload_add_file_template_label":"Download template",
    "institution_label":"Institution",
    "admin_add_btn":"Add",
    "btn_deactivate_label":"Deactivate",
    "btn_activate_label":"Activate",
    "admin_modify_btn":"Update",
    
    "menu_merchants": "MERCHANTS",
    "not_submitted": "Not Submitted",
    "submitted": "Submitted",
    "Declined": "Declined",
    "approved": "Approved",
    "approved_caps": "APPROVED",
    "corrupt_file": "Corrupted File",
    "not_processed": "Not Processed",
    "initiated": "Initiated",
    "count_deposit_label":"Number of Deposits",
    "count_withdrawal_label":"Number of Withdrawals",
    "count_total_label":"Overall Count",
    "amount_deposit_label":"Amount Deposited",
    "amount_withdrawal_label":"Amount Withdrawn",
    "amount_total_label":"Overall Amount",
    "pending":"Pending",
    "failed": "Failed",
    "tranc_id_head":"TRANSACTION ID",
    "reference_head":"REFERENCE",
    "receipt_head":"RECEIPT",
    "accountno_head":"ACCOUNT NO.",
    "wallet_head":"WALLET",
    "wallet_mno_head":"NETWORK",
    "amount_head":"AMOUNT",
    "type_head":"TYPE",
    "frequency_head":"FREQUENCY",
    "status_head":"STATUS",
    "details_head":"DETAILS",
    "date_head":"DATE",
    "success": "Success",
    "region": "REGION",
    "unknown": "Unknown",
    "active": "Active",
    "inactive": "Inactive",
    "wrong_file_format": "Wrong file format.",
    "file_recorded": "File upload successful.",
    "admin_fetched_fail": "Failed to fetched administrators.",
    "customers_fail_msg": "Failed to fetched Customers.",
    "existing_admin": "Username is already in using. Kindly choose another.",
    "existing_Institution": "Short name is already in using. Kindly choose another.",
    "admin_added": "Administrator added successfully.",
    "connection_error": "Connection Error",
    "admin_add_fail": "Failed to add administrator.",
    "admin_updated": "Administrator updated successfully.",
    "admin_update_failed": "Failed to update administrator.",
    "password_mismatch": "Passwords don't match.",
    "weak_password": "Password must be 8 or more charaters",
    "wrong_old_password": "Wrong current password provided.",
    "admin_sucessful_pass_change": "Password changed successfully.",
    "unauthorised_op": "Unauthorised Opteration",
    "file_decline_failed": "Failed to decline payment. Kindly try again later.",
    "file_decline_successful": "Successfully declined payment.",
    "file_approval_failed": "Failed to approve payment. Kindly try again later.",
    "file_approval_successful": "Successfully approved payment.",
    "failed_account_creation": "Could not create merchant virtual account. kindly try again later.",
    "merchant_added": "Merchant Added successfully.",
    "fullname_label":"Full Name",
    "email_label":"Email",
    "amount_label":"Amount",
    "payment_token_label":"Payment Token",
    "bank_label": "Bank",
    "mode_label": "Mode",
    "cash_label": "Cash",
    "cheque_label": "Cheque",
    "transfer_label": "Transfer",
    "username_label": "Username",
    "btn_topup_account_label": "Topup Account",
    "profile_modal_label": "PROFILE",
    "msisdn_label": "Phone Number",
    "current_password_label": "Current Password",
    "new_password_label": "New Password",
    "repeat_password_label": "Retype Password",
    "btn_change_password_label": "Change Password",
    "filter_lable": "Export/Filter",
    "filter_lable_old": "Filter",
    "of_lable": "of",
    "tbl_bulkid_head":"BULK ID.",
    "tbl_file_name_head":"FILE NAME",
    "tbl_size_head":"SIZE",
    "tbl_app_status_head":"APPROVAL STATUS",
    "tbl_processing_status_head":"PROCESSING STATUS",
    "tbl_uploaded_by_head":"UPLOADED BY",
    "tbl_upload_date_head":"UPLOAD DATE",
    "tbl_action_head":"ACTION",
    "upload_add_file_label": "Add file",
    "upload_label": "Upload",
    "upload_cancel_label": "Cancel Upload",
    "upload_file_type_label": "FILE TYPE",
    "pay_details_modal_label": "Payment details",
    "pay_details_info_label": "Info",
    "customer_details_info_label": "Info",
    "pay_details_approval_label": "Approvals",
    "pay_details_label": "Details",
    "pay_details_bulkid_label": "BULK ID",
    "pay_details_filename_label": "FILE NAME",
    "pay_details_appstatus_label": "APPROVAL STATUS",
    "pay_details_proststatus_label": "PROCESSING STATUS",
    "pay_details_currency_label": "CURRENCY",
    "pay_details_amount_label": "AMOUNT",
    "pay_details_username_label": "USERNAME",
    "pay_details_level_label": "USER LEVEL",
    "pay_details_response_label": "RESPONSE",
    "pay_details_date_label": "DATE",
    "pay_details_remarks_label": "REMARKS",
    "bulk_dowload": "Download File",
    "bulk_decline": "Decline",
    "bulk_approve": "Approve",
    "start_date": "From",
    "end_date": "To",
    "bulk_opt_app_status": "Approval Status",
    "bulk_opt_all": "All",
    "bulk_opt_submit": "Submitted",
    "bulk_opt_decline": "Declined",
    "bulk_opt_approve": "Approved",
    "bulk_opt_corrupt_file": "Corrupt File",
    "bulk_opt_pro_status": "Processing Status",
    "bulk_opt_not_proce": "Not Processed",
    "bulk_opt_initiate": "Initiated",
    "bulk_opt_failed": "Failed",
    "bulk_opt_success": "Success",
    "bulk_opt_export": "Export",
    "bulk_opt_filter": "Filter",
    "dash_total_amount_label": "Total amount",
    "dash_amount_success_label": "Total amount successful",
    "dash_amount_failed_label": "Total amount failed",
    "dash_analyse_label": "Analyse",
    "dash_analyse_Desc_label": "By Date",
    "dash_analyse_bnt": "Analyse",
    "trans_tbl_id_head": "TRANSACTION ID.",
    "trans_tbl_ref_head": "FUSION REF. ID",
    "trans_tbl_bulkid_head": "BULK ID",
    "trans_tbl_recv_head": "RECEIVING HSE",
    "trans_tbl_userid_head": "RECEIVING USER ID",
    "trans_tbl_amt_head": "AMOUNT",
    "trans_tbl_status_head": "STATUS",
    "trans_tbl_status_head": "STATUS DETAILS",
    "trans_tbl_exe_head": "EXECUTION TIME",
    "tbl_bulk_details": "Details",
    "filter_status": "Status",
    "opt_uploader": "Uploader",
    "opt_approver1": "Approver1",
    "opt_approver2": "Approver2",
    "opt_approver3": "Approver3",
    "opt_approver4": "Approver4",
    "opt_approver5": "Approver5",
    "approver_level_label": "Approver Level",
    "bulk_active": "Active",
    "bulk_deactivate": "Deactivate",
    "admin_inactive": "Inactive",
    "search_lable": "Search for ...",
    "search_cust_upload_lable": "Search by file name",
    "admin_tbl_username": "USERNAME",
    "admin_tbl_fname": "FIRST NAME",
    "admin_tbl_lname": "LAST NAME",
    "admin_tbl_email": "EMAIL",
    "admin_tbl_msisdn": "PHONE NUMBER",
    "admin_tbl_inst": "INSTITUTION",
    "admin_tbl_utype": "USER TYPE",
    "admin_tbl_status": "STATUS",
    "admin_tbl_cdate": "DATE CREATED",
    "admin_tbl_acttion": "ACTION",
    "admin_add_modal_title": "Add User",
    "admin_modify_modal_title": "Update User",
    "admin_add_modal_label": "Add User",
    "firstname_label": "First Name",
    "lastname_label": "Last Name",
    "username_label": "Username",
    "msisdn_label": "Phone Number",
    "email_label": "Email",
    "usertype_label": "User Type",

    "customer_acc_num": "ACCOUNT NUMBER",
    "created_by": "CREATED BY",
    "date_created": "DATE CREATED",
    "customer_name": "FULL NAME",
    "customer_station": "STATION",
    "customer_wallet": "CUSTOMER WALLET",
    "customer_wallet_mno": "MOBILE WALLET NETWORK",
    "winner_wallet": "PHONE NUMBER",
    "customer_details": "VIEW DETAILS",
    "mm_code" : "MM CODE",


    "transaction_date": "TRANSACTION DATE",
    "amount": "AMOUNT",
    "sms_sent": "SMS SENT",
    "sender": "SENDER",
    "trans_id": "TRANSACTION ID",
    "receipt": "RECEIPT",
    "fusion_ref": "FUSION REF.",
    "cust_id": "CUSTOMER ID",
    "status_details": "STATUS DETAILS",
    "sending_house": "SENDING HOUSE",
    "status": "STATUS",
    "tool":"TOOL",
    "tool_name":"TOOL NAME",
    "tbl_name":"NAME",
    "tbl_tool_price":"TOOL PRICE",
    "tbl_price":"PRICE",
    "tbl_user_number":"USER'S NUMBER",
    "amount_paid":"AMOUNT PAID",
    "fully_paid":"FULLY PAID",
    "payment_details":"PAYMENT DETAILS",
    "redeemed":"REDEEMED",
    "tool_id":"TOOL ID",
    "tool_details":"TOOL DETAILS",
    "date_added":"ADDED ON",
    "last_paid":"LAST PAID",
    "profession":"PROFESSION",
    "tool_type":"TYPE",
    "location":"LOCATION",
    "association":"ASSOCIATION",
    "purchased_tools":"PURCHASED TOOLS",
    "phone_network":"PHONE NETWORK",
    "tbl_update":"UPDATE",
    "updated_by":"UPDATED BY",
    "last_updated":"LAST UPDATED",
    "dealer_name":"DEALER's NAME",
    "dealer_number":"DEALER's NUMBER",
    "artisan_name":"ARTISAN's NAME",
    "artisan_number":"ARTISAN's NUMBER",


}


"""
French language translation
"""
fr = {
    
}

CODES = {
    "FAIL": "01",
    "SUCCESS": "00",
    "ERROR": "02",
}


STYLE = {
    "home_style":{"home":"color:#053856;font-size:12px;font-weight:bolder;"},
    "bosch_style":{"bosch":"color:#053856;font-size:12px;font-weight:bolder;"},
    "dashboard_style":{"dashboard":"color:#053856;font-size:12px;font-weight:bolder;"},
    "trans_style":{"home":"", "bosch":"", "dashboard":"", "transactions":"color:#053856;font-size:12px;font-weight:bolder;", "mainController":"", "inst":"", "mer":"", "topups":""},
    "admins_style":{"home":"", "bosch":"", "dashboard":"", "transactions":"", "mainController":"color:#053856;font-size:12px;font-weight:bolder;", "inst":"", "mer":"", "topups":""},
    "inst_style":{"home":"", "bosch":"", "dashboard":"", "transactions":"", "mainController":"", "inst":"color:#053856;font-size:12px;font-weight:bolder;", "mer":"", "topups":""},
    "mer_style":{"home":"", "dashboard":"", "transactions":"", "mainController":"", "inst":"", "mer":"color:#053856;font-size:12px;font-weight:bolder;", "topups":""},
    "customers_style":{"home":"", "dashboard":"", "transactions":"", "customers":"color:#053856;font-size:12px;font-weight:bolder;", "mainController":"", "inst":"", "mer":"", "topups":""},
    "dealers_style":{"home":"", "dashboard":"", "transactions":"", "dealers":"color:#053856;font-size:12px;font-weight:bolder;font-weight:bolder;", "mainController":"", "inst":"", "mer":"", "topups":""},
    "payment_style":{"home":"", "dashboard":"", "transactions":"", "payments":"color:#053856;font-size:12px;font-weight:bolder;", "mainController":"", "inst":"", "mer":"", "topups":""},
    "tool_style":{"home":"", "dashboard":"", "transactions":"", "tools":"color:#053856;font-size:12px;font-weight:bolder;", "mainController":"", "inst":"", "mer":"", "topups":""},

}